framework:
    workflows:
        creditcard_application_flow:
            type: 'state_machine' # 'workflow' or 'state_machine', defaults to 'workflow'
            marking_store:
                type: 'single_state' # 'single_state or 'multiple_state'
            supports: # the Subject entity. No longer required in Symfony 3.3+
                - AppBundle\Entity\CreditcardApplication
            places:
                - start
                - email_confirmed
                - application_validated
                - card_created
                - card_activated
            transitions:
                confirm_email:
                    from: start
                    to:   email_confirmed
                validate_application:
                    from: email_confirmed
                    to:   application_validated
                create_card:
                    from: application_validated
                    to:   card_created
